# vim: set ft=concourse:
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

params:
  skip_download: true

inputs:
- name: git-branch

outputs:
- name: build-output

caches:
- path: go/

run:
  path: git-branch/.ci/build.sh
