{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "elasticsearch-exporter.fullname" . }}
  labels:
    chart: {{ template "elasticsearch-exporter.chart" . }}
    app: {{ template "elasticsearch-exporter.name" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    {{- if .Values.serviceMonitor.labels }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - interval: {{ .Values.serviceMonitor.scrapeInterval }}
    scrapeTimeout: {{ .Values.es.timeout }}
    honorLabels: true
    port: http
    path: {{ .Values.web.path }}
    scheme: http
  jobLabel: {{ .Release.Name | quote }}
  selector:
    matchLabels:
      app: {{ template "elasticsearch-exporter.name" . }}
      release: {{ .Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
